"use client";
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,AudioLines,BookOpen,Check,ChevronDown,Fingerprint,Heart,Menu,Mic,X,Film,QrCode} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
const stories=[{chapter:'01 / 小時候的家',title:'那扇總為我們留著的門。',text:'小時候，家門口有一棵芒果樹。夏天一到，爸爸就搬張椅子坐在樹下，等我們放學。那時不覺得特別，現在想起來，那就是家的樣子。',question:'你記憶中的家，是什麼模樣？'},{chapter:'02 / 人生的轉彎',title:'第一份薪水，交到媽媽手上。',text:'那年離開家，第一次搭上北上的火車。行李不多，媽媽卻塞滿了一袋吃的。領到第一份薪水時，我買了回家的車票，想親口告訴她：我過得很好。',question:'哪一個決定，改變了你的人生？'},{chapter:'03 / 給以後的你',title:'慢慢走，也會走到你的地方。',text:'如果有一天，你覺得自己走得比別人慢，別著急。阿公年輕時也繞過很多路。有些答案，走著走著才會明白。記得吃飯、好好睡覺，去過你喜歡的生活。',question:'有什麼話，你想留給下一代？'}];
export default function Home(){
const [menu,setMenu]=useState(false),[chapter,setChapter]=useState(0),[purpose,setPurpose]=useState('父母的故事'),[consent,setConsent]=useState(false),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false);
useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!ctx)return;const controller=new AbortController();try{ctx.registerTool({name:'start_story_application',description:'開啟免費人生故事試作申請，可選擇記錄主題；不會提交申請。',inputSchema:{type:'object',properties:{purpose:{type:'string',enum:['父母的故事','自己的故事','家族與手藝']}},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const value=(input as {purpose?:string})?.purpose;if(value&&!['父母的故事','自己的故事','家族與手藝'].includes(value))throw new Error('無效主題');if(value)setPurpose(value);document.getElementById('apply')?.scrollIntoView({behavior:'smooth'});return {opened:true,submitted:false};}},{signal:controller.signal});}catch{}return()=>controller.abort();},[]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!consent){setStatus('請先閱讀並同意資料使用說明。');return;}setBusy(true);setStatus('');const f=new FormData(e.currentTarget);try{const res=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),email:f.get('email'),city:f.get('city'),story:f.get('story'),website:f.get('website'),purpose,consent})});const d=await res.json();if(!res.ok)throw new Error(d.error||'暫時無法送出，請稍後再試。');setSent(true);setStatus('申請已保存。這不是預約確認；我們會依提供的 Email 聯繫討論。');}catch(err){setStatus(err instanceof Error?err.message:'暫時無法送出，請稍後再試。');}finally{setBusy(false);}}
return <><header><a className="brand" href="#" aria-label="留聲首頁"><AudioLines size={30} strokeWidth={1.2}/><span>留聲<small>STORIES THAT STAY</small></span></a><nav className={menu?'open':''}>{[['about','關於留聲'],['services','服務項目'],['story','故事的模樣'],['process','製作流程'],['faq','常見問題']].map(([id,t])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{t}</a>)}</nav><a className="nav-cta" href="#apply">申請免費試作 <ArrowUpRight size={16}/></a><button className="menu" aria-label={menu?'關閉選單':'開啟選單'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/>把不凡的一生，好好收藏</div><h1>有些故事，<br/>值得<span className="emphasis">一再聽見。</span></h1><p className="intro">那些說過好多次的往事，<br/>和還沒來得及說出口的話。<br/>讓我們陪你，留成一本有聲音的人生故事。</p><div className="actions"><a className="button primary" href="#apply">為家人留下一段故事 <ArrowUpRight size={18}/></a><a className="text-link" href="#story">翻開故事示意 <ArrowRight size={17}/></a></div><p className="pilot-note">首批 3 組家庭・免費試作招募中</p></div><figure className="hero-image"><img src="/family-album.webp" alt="長輩與家人一同翻閱老相簿的情境示意"/><div className="photo-caption"><span>每一張老照片，<br/>都有一段還沒說完的故事。</span><AudioLines size={38} strokeWidth={1}/></div><figcaption>情境示意影像，非客戶案例</figcaption></figure><div className="hero-bottom"><span>一段對話，一份留給以後的禮物。</span><a href="#about">往下，開始認識留聲 <ChevronDown size={16}/></a></div></section>
<section id="about" className="about section"><div className="section-label">01 — WHY WE KEEP STORIES</div><div className="about-grid"><h2>在成為爸媽之前，<br/>他們也有自己的<span>故事。</span></h2><div><p>年輕時的夢想、第一次離家、相遇的那一天。<br/>我們熟悉他們的照顧，卻未必聽過他們完整的人生。</p><p>留聲從一次自在的聊天開始，將口述與照片編成故事，再由本人確認。留下文字，也留下聲音裡的笑意與停頓。</p><a className="text-link" href="#process">看看我們如何一起完成 <ArrowRight size={17}/></a></div></div><div className="features"><article><Mic/><h3>留下，真實的聲音</h3><p>保存本人原始錄音。熟悉的語氣，讓回憶不只停在紙上。</p></article><article><BookOpen/><h3>翻閱，一生的片刻</h3><p>把照片與口述整理成故事冊，依需求加印成一本實體書。</p></article><article><Heart/><h3>說給，以後的你</h3><p>為孩子、伴侶或未來的自己，留下一段專屬的話。</p></article></div></section>
<section id="services" className="section services"><div className="section-label">02 — A LIFE, BEAUTIFULLY KEPT</div><div className="services-heading"><h2>你的一生，<br/>值得用喜歡的方式留下。</h2><p>從一次傾聽，到一本書、一段影像。<br/>依你想留下的故事，選擇適合的典藏方式。</p></div><div className="service-grid">
<article><div className="service-mark"><Mic/><span>01 / LISTEN</span></div><h3>到府人生訪談</h3><p>專人到府，陪你慢慢回想。從老照片與日常對話出發，傾聽、梳理人生脈絡，保存屬於你的真實聲音。</p><small>訪談次數、到府地區與交通費用，事前確認。</small></article>
<article><div className="service-mark"><BookOpen/><span>02 / READ</span></div><h3>人生典藏精裝書</h3><p>將口述、照片與重要經歷，編成一本個人自傳。從文字編修到書頁設計，讓一生的篇章成為家人可以珍藏、反覆翻閱的書。</p><small>頁數、裝訂、印製本數與修改範圍，依需求報價。</small></article>
<article><div className="service-mark"><Film/><span>03 / WATCH</span></div><h3>回憶短片・人生紀錄片</h3><p>讓照片裡的時光，再次有了聲音。以既有照片、影片與訪談錄音剪輯回憶短片；也可另行規劃到府拍攝與人物訪談，製作人生紀錄片。</p><small>短片與實地拍攝紀錄片分別規劃，片長與製作費另議。</small></article>
<article><div className="service-mark"><QrCode/><span>04 / REMEMBER</span></div><h3>專屬人生典藏頁</h3><p>用一個專屬 QR Code，連結你的故事、照片與影音。印在書中或紀念卡上，讓家人掃碼，就能走近你的生命記憶。</p><small>分享權限、保存期間與檔案備份方式，製作前共同確認。</small></article>
</div><div className="service-extras"><div><div className="section-label">MORE TO KEEP</div><h3>還有一些，想為你留下。</h3></div><div className="extras-grid"><article><h4>留給重要之人的話</h4><p>為孩子、伴侶或後代，留下一封信或一段親口說出的話，收進書頁與影像裡。</p></article><article><h4>老照片整理與修復</h4><p>掃描、分類並整理照片中的人物與年代；依原件狀況評估褪色、破損修復。</p></article><article><h4>人生新篇續作</h4><p>把新的旅行、家庭相聚與人生轉折，續寫進故事。每次內容與費用另行確認。</p></article></div></div><div className="services-foot"><p>各項服務可依需求搭配，內容與費用另行確認。<br/>目前開放首批免費試作申請，免費範圍以下方方案為準。</p><a className="text-link" href="#pilot">了解免費試作範圍 <ArrowRight size={17}/></a></div></section>
<section id="story" className="story-section section"><div className="story-head"><div><div className="section-label">03 — A GLIMPSE INSIDE</div><h2>翻開一頁，<br/>走近一個人的一生。</h2></div><p>文字內容示意，非真實客戶故事。<br/>你的成品，會保留屬於你的說話方式。</p></div><div className="story-layout"><div className="chapter-nav" aria-label="故事章節">{stories.map((s,i)=><button key={s.chapter} aria-pressed={chapter===i} className={chapter===i?'selected':''} onClick={()=>setChapter(i)}><span>{s.chapter}</span><ArrowUpRight size={20}/></button>)}<div className="chapter-note"><Fingerprint size={28}/><p>用心整理回憶，<br/>人生由你親自定稿。</p></div></div><article className="story-page"><div className="page-top"><span>留聲・人生故事節錄</span><span>示意稿</span></div><h3>{stories[chapter].title}</h3><p>{stories[chapter].text}</p><div className="prompt"><AudioLines size={22}/><div><small>從這個問題開始</small><p>{stories[chapter].question}</p></div></div><div className="page-bottom"><span>每一段回憶，都值得被好好聽見。</span><span>0{chapter+1}</span></div></article></div></section>
<section id="process" className="section process"><div className="section-label">04 — MADE TOGETHER</div><h2>不用會寫作。<span>從聊天開始就好。</span></h2><div className="steps">{[['01','聊聊想留下的事','一起選定主角、記錄主題與分享對象，確認受訪者的意願。'],['02','聽你說，陪你整理','透過訪談與老照片，慢慢回想。你可以跳過任何不想談的內容。'],['03','把回憶編成故事','我們整理訪談內容、編修文字與版面，再交由本人核對與修改。'],['04','交到你與家人手上','交付故事冊與原始錄音；確認後可加印成書，之後也能續作新篇章。']].map(([n,t,p])=><article key={n}><span className="step-no">{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
<section id="pilot" className="invitation section"><div><div className="section-label">THE FIRST CHAPTER</div><h2>第一批故事，<br/>想邀請你一起完成。</h2><p>我們正在建立最初的作品與製作流程，<br/>招募 3 組願意分享、一起提供回饋的家庭。</p><p className="fine">是否公開作品另行徵求同意。<br/>參與免費試作，不代表同意公開個人故事。</p></div><div className="offer"><div className="offer-top"><span>人生故事・免費試作</span><span className="pill">首批招募</span></div><div className="price">NT$ 0 <span>／ 入選家庭</span></div><ul>{['一位主角，約 60–90 分鐘訪談','10–15 張照片・12–20 頁 PDF 故事冊','原始錄音與 3–5 段精選聲音連結','一次整合修改與完成後回饋'].map(t=><li key={t}><Check size={16}/>{t}</li>)}</ul><p>免費試作僅包含以上項目；精裝印書、影片製作、專屬典藏頁、照片修復與續作不包含在內，另行確認報價。到府安排與交通費用事前確認。申請不保證入選。</p><a className="button primary" href="#apply">申請這次免費試作 <ArrowUpRight size={18}/></a></div></section>
<section id="apply" className="section application"><div className="application-intro"><div className="section-label">05 — LET’S START YOUR STORY</div><h2>你想留下，<br/>誰的故事？</h2><p>先告訴我們一點點。<br/>不用準備完整資料，也不用現在就決定所有細節。</p><div className="privacy"><Fingerprint size={24}/><p>此表單只用於試作評估與聯繫。<br/>請先不要上傳照片或填寫私密人生細節。</p></div></div><form onSubmit={submit}><fieldset disabled={busy||sent}><legend>我想記錄的是</legend><RadioGroup value={purpose} onValueChange={setPurpose} className="purposes">{['父母的故事','自己的故事','家族與手藝'].map((p,i)=><label key={p} className={purpose===p?'active':''}><RadioGroupItem id={'purpose-'+i} value={p}/>{p}</label>)}</RadioGroup><div className="fields"><label>你的稱呼<input name="name" required maxLength={60} autoComplete="name" placeholder="我們該怎麼稱呼你？"/></label><label>Email<input name="email" type="email" required maxLength={200} autoComplete="email" placeholder="用來聯繫討論"/></label></div><label>所在縣市<input name="city" required maxLength={60} placeholder="例如：新北市三重區"/></label><label>為什麼想開始記錄？<span className="optional">（選填）</span><textarea name="story" maxLength={1500} rows={3} placeholder="例如：爸爸明年要退休，想把他經營店面的故事留下來。"/></label><input name="website" className="trap" tabIndex={-1} autoComplete="off" aria-hidden="true"/><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="同意資料使用說明"/><span>我同意留聲保存上述資料，用於本次試作評估與聯繫；不作為公開作品或廣告素材。可於後續聯繫時要求更正或刪除。</span></label><button className="button primary submit" type="submit" disabled={!consent||busy||sent}>{busy?'正在送出…':sent?'申請已送出':'送出試作申請'}{sent?<Check size={18}/>:<ArrowUpRight size={18}/>}</button><p role="status" className={sent?'form-status success':'form-status'}>{status}</p></fieldset></form></section>
<section id="faq" className="section faq"><div><div className="section-label">A FEW THINGS TO KNOW</div><h2>開始之前，<br/>你可能想知道。</h2></div><div>{[['長輩不會使用電腦，也能參加嗎？','可以。受訪者只需要自在分享，家人可協助安排訪談與提供照片。訪談方式與地點會先共同確認。'],['故事內容會如何確認？','我們以你的口述與提供的資料為依據，不以虛構情節補足記憶。不確定的人名、年份與細節會標記確認，定稿交由本人核對。'],['故事會公開在網路上嗎？','不會因為參與試作就自動公開。作品的分享對象與公開節錄，會另外取得當事人同意。'],['QR code 裡的聲音會保存多久？','QR code 連結到影音頁面，本身不儲存錄音。線上保存期間會在製作前確認，並提供原始錄音及 PDF 下載，讓家庭自行備份。'],['之後可以加印或繼續記錄嗎？','可以提出加印與續作需求，例如新的家庭故事、紀念日或給孩子的話。內容範圍與價格會在開始前另行確認，不會自動扣款。']].map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section></main>
<footer><a className="brand" href="#"><AudioLines size={28} strokeWidth={1.2}/><span>留聲<small>STORIES THAT STAY</small></span></a><p>把今天的聲音，留給以後的想念。</p><span>© {new Date().getFullYear()} 留聲 · 人生故事典藏</span></footer></>;
}
